# Generated by Django 4.1 on 2022-08-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0002_alter_employeemodel_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='department_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='manager_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
