# Generated by Django 4.1 on 2022-08-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0003_alter_employeemodel_department_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='hire_date',
            field=models.DateField(),
        ),
    ]
