# Generated by Django 4.1 on 2022-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0004_alter_employeemodel_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='job_id',
            field=models.CharField(max_length=10),
        ),
    ]
