# Generated by Django 4.1 on 2022-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0005_alter_employeemodel_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('job_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=35)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-job_id'],
            },
        ),
    ]
