# Generated by Django 4.1 on 2022-08-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0006_jobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uiapp.jobmodel'),
        ),
    ]
