# Generated by Django 4.1 on 2022-08-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0008_alter_employeemodel_manager_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='department_id',
        ),
        migrations.CreateModel(
            name='DepartmentsModel',
            fields=[
                ('department_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=30)),
                ('location_id', models.SmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uiapp.employeemodel')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['-department_id'],
            },
        ),
    ]
